# Fly.io deployment configuration for Claude Code UI Cloud
app = "claude-code-ui"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  CLOUD_MODE = "true"
  PORT = "3000"

# Database volume for persistent SQLite storage
[mounts]
  source = "claude_data"
  destination = "/app/data"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/api/config"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false

# WebSocket support
[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [[services.ports]]
    port = 3001
    handlers = ["http"]
    
# Environment variables (set these via `fly secrets set`)
# JWT_SECRET=your-super-secret-jwt-key
# API_KEY=optional-api-key-for-additional-security